services:
  postgres:
    image: postgres
    container_name: money-manager-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: local
      POSTGRES_PASSWORD: pass123
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local -d db"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  backend:
    build: .
    ports:
      - "45000:45000"
    environment:
      - NODE_ENV=production
    depends_on:
      postgres:
        condition: service_healthy